In [ ]:
def convert_units(conversion_type, value):
    try:
        value = float(value)
    except ValueError:
        return "Invalid input. Please enter a numeric value."

    if conversion_type == 'length':
        unit_from = input("Enter the unit to convert from (m or ft): ").lower()
        if unit_from == 'm':
            converted_value = value * 3.28084
            return f"{value} meters is equal to {converted_value} feet"
        elif unit_from == 'ft':
            converted_value = value / 3.28084
            return f"{value} feet is equal to {converted_value} meters"
        else:
            return "Invalid unit for length conversion."
    elif conversion_type == 'weight':
        unit_from = input("Enter the unit to convert from (kg or lbs): ").lower()
        if unit_from == 'kg':
            converted_value = value * 2.20462
            return f"{value} kilograms is equal to {converted_value} pounds"
        elif unit_from == 'lbs':
            converted_value = value / 2.20462
            return f"{value} pounds is equal to {converted_value} kilograms"
        else:
            return "Invalid unit for weight conversion."
    elif conversion_type == 'volume':
        unit_from = input("Enter the unit to convert from (L or gal): ").lower()
        if unit_from == 'l':
            converted_value = value * 0.264172
            return f"{value} liters is equal to {converted_value} gallons"
        elif unit_from == 'gal':
            converted_value = value / 0.264172
            return f"{value} gallons is equal to {converted_value} liters"
        else:
            return "Invalid unit for volume conversion."
    else:
        return "Invalid conversion type."


if __name__ == "__main__":
    conversion_type = input("Enter the type of conversion (length, weight, volume): ").lower()
    value = input("Enter the value to convert: ")
    result = convert_units(conversion_type, value)
result

Enter the type of conversion (length, weight, volume): length
Enter the value to convert: 6
Enter the unit to convert from (m or ft): ft


'6.0 feet is equal to 1.828799941478402 meters'

In [ ]:
def calculate_sum(numbers):
  try:
    return sum(numbers)
  except TypeError:
    return "Invalid input: List must contain only numbers."

def calculate_average(numbers):
  try:
    if not numbers:
      return "Invalid input: List cannot be empty."
    return sum(numbers) / len(numbers)
  except TypeError:
    return "Invalid input: List must contain only numbers."

def find_maximum(numbers):
  try:
    if not numbers:
      return "Invalid input: List cannot be empty."
    return max(numbers)
  except TypeError:
    return "Invalid input: List must contain only numbers."

def find_minimum(numbers):
  try:
    if not numbers:
      return "Invalid input: List cannot be empty."
    return min(numbers)
  except TypeError:
    return "Invalid input: List must contain only numbers."

if __name__ == "__main__":
  print("Select an operation:")
  print("1. Calculate Sum")
  print("2. Calculate Average")
  print("3. Find Maximum")
  print("4. Find Minimum")

  choice = input("Enter your choice (1-4): ")

  try:
    numbers_str = input("Enter a list of numbers separated by spaces: ")
    numbers = [float(x) for x in numbers_str.split()]

    if choice == '1':
      result = calculate_sum(numbers)
    elif choice == '2':
      result = calculate_average(numbers)
    elif choice == '3':
      result = find_maximum(numbers)
    elif choice == '4':
      result = find_minimum(numbers)
    else:
      result = "Invalid choice. Please enter a number between 1 and 4."

    print(result)

  except ValueError:
    print("Invalid input: Please enter numbers only.")

Select an operation:
1. Calculate Sum
2. Calculate Average
3. Find Maximum
4. Find Minimum
Enter your choice (1-4): 2
Enter a list of numbers separated by spaces: 1241 11231 12312
8261.333333333334


In [ ]:
def extract_every_other(lst):
  return lst[::2]
my_list = [1,2,3,4,5]
extract_every_other(my_list)

[1, 3, 5]

In [ ]:
def get_sublist(lst, start, end):
  return lst[start:end+1]
get_sublist(my_list, 2, 4)

[3, 4, 5]

In [ ]:
def reverse_list(lst):
  return lst[::-1]
reverse_list(my_list)

[5, 4, 3, 2, 1]

In [ ]:
def remove_first_last(lst):
  return lst[1:-1]
remove_first_last(my_list)

[2, 3, 4]

In [ ]:
def get_first_n(lst):
  return lst[:3]
get_first_n(my_list)

[1, 2, 3]

In [ ]:
def get_last_n(lst):
  return lst[-2:]
get_last_n(my_list)

[4, 5]

In [ ]:
def reverse_ski(lst):
  return lst[::-2]
reverse_ski(my_list)

[5, 3, 1]

In [ ]:
def flatten(lst):
  flat_list = []
  for sublist in lst:
    for item in sublist:
      flat_list.append(item)
  return flat_list
nested_list = [[1,2],[3,4],[5]]
flatten(nested_list)

[1, 2, 3, 4, 5]

In [ ]:
def access_nested_element(lst, indices):
    try:
        element = lst
        for index in indices:
            element = element[index]
        return element
    except IndexError:
        return None
lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
result = access_nested_element(lst, indices)
print(result)

6


In [ ]:
def sum_nested(lst):
  total = 0
  for element in lst:
    if isinstance(element, list):
      total += sum_nested(element)
    elif isinstance(element, int):
      total += element
  return total
nested_list = [1, [2, 3, [4, 5]], 6]
sum_nested(nested_list)

21

In [ ]:
def remove_element(lst, elem):
  new_list = []
  for sublist in lst:
    new_sublist = []
    for item in sublist:
      if item != elem:
        new_sublist.append(item)
    new_list.append(new_sublist)
  return new_list
nested_list = [[1, 2], [3, 2], [4, 5]]
remove_element(nested_list, 2)

[[1], [3], [4, 5]]

In [ ]:
def find_max(lst):
    max_element = -float('inf')
    for element in lst:
        if isinstance(element, list):
            max_element = max(max_element, find_max(element))
        elif isinstance(element, int) or isinstance(element, float):
            max_element = max(max_element, element)
    return max_element
lst = [1, 2, [3, 4, [5, 6]], 7]
find_max(lst)

7

In [ ]:
def count_occurrences(lst, elem):
  count = 0
  for sublist in lst:
    for item in sublist:
      if item == elem:
        count += 1
  return count

lst = [[1, 2], [2, 3], [2, 4]]
elem = 2
occurrences = count_occurrences(lst, elem)
print(f"The element {elem} appears {occurrences} times in the list.")

The element 2 appears 3 times in the list.


In [ ]:
def deep_flatten(lst):
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))
        else:
            flat_list.append(item)
    return flat_list
lst = [[[1],[2],[3],[4],[5]],[[6,7],[8,9]]]
deep_flatten(lst)

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
def average_nested(lst):
  total_sum = 0
  total_count = 0

  for sublist in lst:
    if not isinstance(sublist, list):
      return "Invalid input: Sublists must be lists."
    for element in sublist:
      if not isinstance(element, (int, float)):
        return "Invalid input: Elements must be numbers."
      total_sum += element
      total_count += 1

  if total_count == 0:
    return "Invalid input: The list cannot be empty."

  return total_sum / total_count
lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
average_nested(lst)

5.0

In [ ]:
import numpy as np

empty_array = np.empty((2, 2))

ones_array = np.ones((4, 2))

fill_array = np.full((3, 3), 5)

example_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(example_array)

ones_like_array = np.ones_like(example_array)

new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)


print("Empty Array:\n", empty_array)
print("\nOnes Array:\n", ones_array)
print("\nFill Array:\n", fill_array)
print("\nZeros Like Array:\n", zeros_like_array)
print("\nOnes Like Array:\n", ones_like_array)
print("\nNumpy Array from List:\n", numpy_array)

Empty Array:
 [[5.e-324 5.e-324]
 [5.e-324 5.e-324]]

Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Fill Array:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]

Zeros Like Array:
 [[0 0]
 [0 0]]

Ones Like Array:
 [[1 1]
 [1 1]]

Numpy Array from List:
 [1 2 3 4]


In [ ]:
import numpy as np

array_1 = np.arange(10, 50)
print("Array with values from 10 to 49:\n", array_1)

matrix_1 = np.arange(0, 9).reshape(3, 3)
print("\n3x3 matrix with values from 0 to 8:\n", matrix_1)

identity_matrix = np.eye(3)
print("\n3x3 identity matrix:\n", identity_matrix)

random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom array of size 30:\n", random_array)
print("\nMean of the random array:", mean_value)

random_array_10x10 = np.random.random((10, 10))
min_value = random_array_10x10.min()
max_value = random_array_10x10.max()
print("\n10x10 array with random values:\n", random_array_10x10)
print("\nMinimum value:", min_value)
print("Maximum value:", max_value)

zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero array with 5th element replaced by 1:\n", zero_array)

arr = [1, 2, 0, 0, 4, 0]
reversed_arr = arr[::-1]
print("\nReversed array:", reversed_arr)

array_2d = np.ones((5, 5))
array_2d[1:-1, 1:-1] = 0
print("\n2D array with 1 on border and 0 inside:\n", array_2d)

checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 matrix with checkerboard pattern:\n", checkerboard)

Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random array of size 30:
 [0.93601237 0.94077206 0.30783847 0.31819609 0.62343002 0.89645361
 0.83301508 0.9115115  0.18069101 0.86419214 0.58117636 0.8717942
 0.74974409 0.86417173 0.34643789 0.61601585 0.58900405 0.85657826
 0.07231506 0.46207567 0.79657769 0.90998852 0.3605613  0.6211574
 0.82865318 0.11481363 0.0074488  0.45697348 0.89521553 0.43842223]

Mean of the random array: 0.6083745759274443

10x10 array with random values:
 [[0.2735121  0.32638035 0.98180451 0.58840325 0.57130217 0.91800673
  0.08590198 0.88482257 0.70045362 0.58155827]
 [0.75979509 0.94475335 0.84560388 0.1808436  0.57968324 0.22635981
  0.57245277 0.87306798 0.7351081  0.91214669]
 [0.89471676 0.44190901 0.51268899 0.99200567 

In [ ]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

print("Sum of x and y:\n",x + y)

print("Difference of x and y:\n",x - y)

print("x multiplied by 3:\n", x * 3)

print("Square of elements in x:\n", x**2)

print("Dot product of v and w:", v.dot(w))
print("Dot product of x and v:\n", x.dot(v))
print("Dot product of x and y:\n", x.dot(y))

print("Concatenate x and y along rows:\n",np.concatenate((x,y),axis=0))
print("Concatenate v and w along columns:\n",np.vstack((v,w)))


print("Concatenate x and v (corrected):\n",np.concatenate((x,v.reshape(1,2)),axis=0))


Sum of x and y:
 [[ 6  8]
 [10 13]]
Difference of x and y:
 [[-4 -4]
 [-4 -3]]
x multiplied by 3:
 [[ 3  6]
 [ 9 15]]
Square of elements in x:
 [[ 1  4]
 [ 9 25]]
Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]
Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
 [[ 9 10]
 [11 12]]
Concatenate x and v (corrected):
 [[ 1  2]
 [ 3  5]
 [ 9 10]]


In [ ]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print("A.A−1 = I:\n", I)

B = np.array([[5, 3], [2, 1]])
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:\n", AB)
print("\nBA:\n", BA)
print("\nAB != BA:", not np.array_equal(AB, BA))

AB_T = np.transpose(AB)
B_T = np.transpose(B)
A_T = np.transpose(A)
BT_AT = np.dot(B_T, A_T)
print("\n(AB)T:\n", AB_T)
print("\nBTAT:\n", BT_AT)
print("\n(AB)T = BTAT:", np.array_equal(AB_T, BT_AT))

A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])
X = np.linalg.solve(A, B)
print("\nSolution using np.linalg.solve:\n", X)

A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print("\nSolution using np.linalg.inv:\n", X)

A.A−1 = I:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]

AB != BA: True

(AB)T:
 [[23 51]
 [13 29]]

BTAT:
 [[23 51]
 [13 29]]

(AB)T = BTAT: True

Solution using np.linalg.solve:
 [ 2.  1. -2.]

Solution using np.linalg.inv:
 [ 2.  1. -2.]
